<?xml version="1.0" encoding="utf-8"?><Database Name="BD_Mundo" Class="DBMundoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=BD_Mundo;Integrated Security=True" SettingsObjectName="DAL_Mundo.Properties.Settings" SettingsPropertyName="BD_MundoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Continentes" Member="Continentes">
    <Type Name="Continentes">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="continente" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Continentes_paises" Member="paises" ThisKey="id" OtherKey="continente_id" Type="paises" />
    </Type>
  </Table>
  <Table Name="dbo.Gobiernos" Member="Gobiernos">
    <Type Name="Gobiernos">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="gobierno" Type="System.String" DbType="VarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Gobiernos_paises" Member="paises" ThisKey="id" OtherKey="gobierno_id" Type="paises" />
    </Type>
  </Table>
  <Table Name="dbo.idiomas" Member="idiomas">
    <Type Name="idiomas">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idioma" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="idiomas_paises_idiomas" Member="paises_idiomas" ThisKey="id" OtherKey="idioma_id" Type="paises_idiomas" />
    </Type>
  </Table>
  <Table Name="dbo.paises" Member="paises">
    <Type Name="paises">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pais" Type="System.String" DbType="VarChar(35) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="capital" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="moneda" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="continente_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gobierno_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="poblacion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="extension" Type="System.Decimal" DbType="Decimal(15,5)" CanBeNull="true" />
      <Column Name="posicion" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="existe" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="costa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="country" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="code" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Association Name="paises_paises_idiomas" Member="paises_idiomas" ThisKey="id" OtherKey="pais_id" Type="paises_idiomas" />
      <Association Name="paises_paises_vecinos" Member="paises_vecinos" ThisKey="id" OtherKey="pais_id" Type="paises_vecinos" />
      <Association Name="paises_paises_vecinos1" Member="paises_vecinos1" ThisKey="id" OtherKey="vecino_id" Type="paises_vecinos" />
      <Association Name="Continentes_paises" Member="Continentes" ThisKey="continente_id" OtherKey="id" Type="Continentes" IsForeignKey="true" />
      <Association Name="Gobiernos_paises" Member="Gobiernos" ThisKey="gobierno_id" OtherKey="id" Type="Gobiernos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.paises_idiomas" Member="paises_idiomas">
    <Type Name="paises_idiomas">
      <Column Name="pais_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idioma_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="hablantes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="porcentaje" Type="System.Decimal" DbType="Decimal(15,5)" CanBeNull="true" />
      <Association Name="idiomas_paises_idiomas" Member="idiomas" ThisKey="idioma_id" OtherKey="id" Type="idiomas" IsForeignKey="true" />
      <Association Name="paises_paises_idiomas" Member="paises" ThisKey="pais_id" OtherKey="id" Type="paises" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.paises_vecinos" Member="paises_vecinos">
    <Type Name="paises_vecinos">
      <Column Name="pais_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="vecino_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="kms_frontera" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="paises_paises_vecinos" Member="paises" ThisKey="pais_id" OtherKey="id" Type="paises" IsForeignKey="true" />
      <Association Name="paises_paises_vecinos1" Member="paises1" ThisKey="vecino_id" OtherKey="id" Type="paises" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.PaisContinente" Method="PaisContinente">
    <ElementType Name="PaisContinenteResult">
      <Column Name="pais" Type="System.String" DbType="VarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="continente" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>