#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Mundo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_Mundo")]
	public partial class DBMundoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertContinentes(Continentes instance);
    partial void UpdateContinentes(Continentes instance);
    partial void DeleteContinentes(Continentes instance);
    partial void InsertGobiernos(Gobiernos instance);
    partial void UpdateGobiernos(Gobiernos instance);
    partial void DeleteGobiernos(Gobiernos instance);
    partial void Insertidiomas(idiomas instance);
    partial void Updateidiomas(idiomas instance);
    partial void Deleteidiomas(idiomas instance);
    partial void Insertpaises(paises instance);
    partial void Updatepaises(paises instance);
    partial void Deletepaises(paises instance);
    partial void Insertpaises_idiomas(paises_idiomas instance);
    partial void Updatepaises_idiomas(paises_idiomas instance);
    partial void Deletepaises_idiomas(paises_idiomas instance);
    partial void Insertpaises_vecinos(paises_vecinos instance);
    partial void Updatepaises_vecinos(paises_vecinos instance);
    partial void Deletepaises_vecinos(paises_vecinos instance);
    #endregion
		
		public DBMundoDataContext() : 
				base(global::DAL_Mundo.Properties.Settings.Default.BD_MundoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBMundoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMundoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMundoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMundoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Continentes> Continentes
		{
			get
			{
				return this.GetTable<Continentes>();
			}
		}
		
		public System.Data.Linq.Table<Gobiernos> Gobiernos
		{
			get
			{
				return this.GetTable<Gobiernos>();
			}
		}
		
		public System.Data.Linq.Table<idiomas> idiomas
		{
			get
			{
				return this.GetTable<idiomas>();
			}
		}
		
		public System.Data.Linq.Table<paises> paises
		{
			get
			{
				return this.GetTable<paises>();
			}
		}
		
		public System.Data.Linq.Table<paises_idiomas> paises_idiomas
		{
			get
			{
				return this.GetTable<paises_idiomas>();
			}
		}
		
		public System.Data.Linq.Table<paises_vecinos> paises_vecinos
		{
			get
			{
				return this.GetTable<paises_vecinos>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PaisContinente")]
		public ISingleResult<PaisContinenteResult> PaisContinente()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<PaisContinenteResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Continentes")]
	public partial class Continentes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _continente;
		
		private EntitySet<paises> _paises;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncontinenteChanging(string value);
    partial void OncontinenteChanged();
    #endregion
		
		public Continentes()
		{
			this._paises = new EntitySet<paises>(new Action<paises>(this.attach_paises), new Action<paises>(this.detach_paises));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_continente", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string continente
		{
			get
			{
				return this._continente;
			}
			set
			{
				if ((this._continente != value))
				{
					this.OncontinenteChanging(value);
					this.SendPropertyChanging();
					this._continente = value;
					this.SendPropertyChanged("continente");
					this.OncontinenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Continentes_paises", Storage="_paises", ThisKey="id", OtherKey="continente_id")]
		public EntitySet<paises> paises
		{
			get
			{
				return this._paises;
			}
			set
			{
				this._paises.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_paises(paises entity)
		{
			this.SendPropertyChanging();
			entity.Continentes = this;
		}
		
		private void detach_paises(paises entity)
		{
			this.SendPropertyChanging();
			entity.Continentes = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Gobiernos")]
	public partial class Gobiernos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _gobierno;
		
		private EntitySet<paises> _paises;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OngobiernoChanging(string value);
    partial void OngobiernoChanged();
    #endregion
		
		public Gobiernos()
		{
			this._paises = new EntitySet<paises>(new Action<paises>(this.attach_paises), new Action<paises>(this.detach_paises));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gobierno", DbType="VarChar(40) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string gobierno
		{
			get
			{
				return this._gobierno;
			}
			set
			{
				if ((this._gobierno != value))
				{
					this.OngobiernoChanging(value);
					this.SendPropertyChanging();
					this._gobierno = value;
					this.SendPropertyChanged("gobierno");
					this.OngobiernoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Gobiernos_paises", Storage="_paises", ThisKey="id", OtherKey="gobierno_id")]
		public EntitySet<paises> paises
		{
			get
			{
				return this._paises;
			}
			set
			{
				this._paises.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_paises(paises entity)
		{
			this.SendPropertyChanging();
			entity.Gobiernos = this;
		}
		
		private void detach_paises(paises entity)
		{
			this.SendPropertyChanging();
			entity.Gobiernos = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.idiomas")]
	public partial class idiomas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _idioma;
		
		private EntitySet<paises_idiomas> _paises_idiomas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidiomaChanging(string value);
    partial void OnidiomaChanged();
    #endregion
		
		public idiomas()
		{
			this._paises_idiomas = new EntitySet<paises_idiomas>(new Action<paises_idiomas>(this.attach_paises_idiomas), new Action<paises_idiomas>(this.detach_paises_idiomas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idioma", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idioma
		{
			get
			{
				return this._idioma;
			}
			set
			{
				if ((this._idioma != value))
				{
					this.OnidiomaChanging(value);
					this.SendPropertyChanging();
					this._idioma = value;
					this.SendPropertyChanged("idioma");
					this.OnidiomaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="idiomas_paises_idiomas", Storage="_paises_idiomas", ThisKey="id", OtherKey="idioma_id")]
		public EntitySet<paises_idiomas> paises_idiomas
		{
			get
			{
				return this._paises_idiomas;
			}
			set
			{
				this._paises_idiomas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_paises_idiomas(paises_idiomas entity)
		{
			this.SendPropertyChanging();
			entity.idiomas = this;
		}
		
		private void detach_paises_idiomas(paises_idiomas entity)
		{
			this.SendPropertyChanging();
			entity.idiomas = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.paises")]
	public partial class paises : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _pais;
		
		private string _capital;
		
		private string _moneda;
		
		private System.Nullable<int> _continente_id;
		
		private System.Nullable<int> _gobierno_id;
		
		private System.Nullable<int> _poblacion;
		
		private System.Nullable<decimal> _extension;
		
		private string _posicion;
		
		private bool _existe;
		
		private System.Nullable<int> _costa;
		
		private string _country;
		
		private string _code;
		
		private EntitySet<paises_idiomas> _paises_idiomas;
		
		private EntitySet<paises_vecinos> _paises_vecinos;
		
		private EntitySet<paises_vecinos> _paises_vecinos1;
		
		private EntityRef<Continentes> _Continentes;
		
		private EntityRef<Gobiernos> _Gobiernos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnpaisChanging(string value);
    partial void OnpaisChanged();
    partial void OncapitalChanging(string value);
    partial void OncapitalChanged();
    partial void OnmonedaChanging(string value);
    partial void OnmonedaChanged();
    partial void Oncontinente_idChanging(System.Nullable<int> value);
    partial void Oncontinente_idChanged();
    partial void Ongobierno_idChanging(System.Nullable<int> value);
    partial void Ongobierno_idChanged();
    partial void OnpoblacionChanging(System.Nullable<int> value);
    partial void OnpoblacionChanged();
    partial void OnextensionChanging(System.Nullable<decimal> value);
    partial void OnextensionChanged();
    partial void OnposicionChanging(string value);
    partial void OnposicionChanged();
    partial void OnexisteChanging(bool value);
    partial void OnexisteChanged();
    partial void OncostaChanging(System.Nullable<int> value);
    partial void OncostaChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    #endregion
		
		public paises()
		{
			this._paises_idiomas = new EntitySet<paises_idiomas>(new Action<paises_idiomas>(this.attach_paises_idiomas), new Action<paises_idiomas>(this.detach_paises_idiomas));
			this._paises_vecinos = new EntitySet<paises_vecinos>(new Action<paises_vecinos>(this.attach_paises_vecinos), new Action<paises_vecinos>(this.detach_paises_vecinos));
			this._paises_vecinos1 = new EntitySet<paises_vecinos>(new Action<paises_vecinos>(this.attach_paises_vecinos1), new Action<paises_vecinos>(this.detach_paises_vecinos1));
			this._Continentes = default(EntityRef<Continentes>);
			this._Gobiernos = default(EntityRef<Gobiernos>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pais", DbType="VarChar(35) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string pais
		{
			get
			{
				return this._pais;
			}
			set
			{
				if ((this._pais != value))
				{
					this.OnpaisChanging(value);
					this.SendPropertyChanging();
					this._pais = value;
					this.SendPropertyChanged("pais");
					this.OnpaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capital", DbType="VarChar(20)")]
		public string capital
		{
			get
			{
				return this._capital;
			}
			set
			{
				if ((this._capital != value))
				{
					this.OncapitalChanging(value);
					this.SendPropertyChanging();
					this._capital = value;
					this.SendPropertyChanged("capital");
					this.OncapitalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moneda", DbType="VarChar(30)")]
		public string moneda
		{
			get
			{
				return this._moneda;
			}
			set
			{
				if ((this._moneda != value))
				{
					this.OnmonedaChanging(value);
					this.SendPropertyChanging();
					this._moneda = value;
					this.SendPropertyChanged("moneda");
					this.OnmonedaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_continente_id", DbType="Int")]
		public System.Nullable<int> continente_id
		{
			get
			{
				return this._continente_id;
			}
			set
			{
				if ((this._continente_id != value))
				{
					if (this._Continentes.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncontinente_idChanging(value);
					this.SendPropertyChanging();
					this._continente_id = value;
					this.SendPropertyChanged("continente_id");
					this.Oncontinente_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gobierno_id", DbType="Int")]
		public System.Nullable<int> gobierno_id
		{
			get
			{
				return this._gobierno_id;
			}
			set
			{
				if ((this._gobierno_id != value))
				{
					if (this._Gobiernos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ongobierno_idChanging(value);
					this.SendPropertyChanging();
					this._gobierno_id = value;
					this.SendPropertyChanged("gobierno_id");
					this.Ongobierno_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_poblacion", DbType="Int")]
		public System.Nullable<int> poblacion
		{
			get
			{
				return this._poblacion;
			}
			set
			{
				if ((this._poblacion != value))
				{
					this.OnpoblacionChanging(value);
					this.SendPropertyChanging();
					this._poblacion = value;
					this.SendPropertyChanged("poblacion");
					this.OnpoblacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_extension", DbType="Decimal(15,5)")]
		public System.Nullable<decimal> extension
		{
			get
			{
				return this._extension;
			}
			set
			{
				if ((this._extension != value))
				{
					this.OnextensionChanging(value);
					this.SendPropertyChanging();
					this._extension = value;
					this.SendPropertyChanged("extension");
					this.OnextensionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_posicion", DbType="VarChar(20)")]
		public string posicion
		{
			get
			{
				return this._posicion;
			}
			set
			{
				if ((this._posicion != value))
				{
					this.OnposicionChanging(value);
					this.SendPropertyChanging();
					this._posicion = value;
					this.SendPropertyChanged("posicion");
					this.OnposicionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_existe", DbType="Bit NOT NULL")]
		public bool existe
		{
			get
			{
				return this._existe;
			}
			set
			{
				if ((this._existe != value))
				{
					this.OnexisteChanging(value);
					this.SendPropertyChanging();
					this._existe = value;
					this.SendPropertyChanged("existe");
					this.OnexisteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costa", DbType="Int")]
		public System.Nullable<int> costa
		{
			get
			{
				return this._costa;
			}
			set
			{
				if ((this._costa != value))
				{
					this.OncostaChanging(value);
					this.SendPropertyChanging();
					this._costa = value;
					this.SendPropertyChanged("costa");
					this.OncostaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="VarChar(35)")]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this.OncountryChanging(value);
					this.SendPropertyChanging();
					this._country = value;
					this.SendPropertyChanged("country");
					this.OncountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(2)")]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="paises_paises_idiomas", Storage="_paises_idiomas", ThisKey="id", OtherKey="pais_id")]
		public EntitySet<paises_idiomas> paises_idiomas
		{
			get
			{
				return this._paises_idiomas;
			}
			set
			{
				this._paises_idiomas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="paises_paises_vecinos", Storage="_paises_vecinos", ThisKey="id", OtherKey="pais_id")]
		public EntitySet<paises_vecinos> paises_vecinos
		{
			get
			{
				return this._paises_vecinos;
			}
			set
			{
				this._paises_vecinos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="paises_paises_vecinos1", Storage="_paises_vecinos1", ThisKey="id", OtherKey="vecino_id")]
		public EntitySet<paises_vecinos> paises_vecinos1
		{
			get
			{
				return this._paises_vecinos1;
			}
			set
			{
				this._paises_vecinos1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Continentes_paises", Storage="_Continentes", ThisKey="continente_id", OtherKey="id", IsForeignKey=true)]
		public Continentes Continentes
		{
			get
			{
				return this._Continentes.Entity;
			}
			set
			{
				Continentes previousValue = this._Continentes.Entity;
				if (((previousValue != value) 
							|| (this._Continentes.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Continentes.Entity = null;
						previousValue.paises.Remove(this);
					}
					this._Continentes.Entity = value;
					if ((value != null))
					{
						value.paises.Add(this);
						this._continente_id = value.id;
					}
					else
					{
						this._continente_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Continentes");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Gobiernos_paises", Storage="_Gobiernos", ThisKey="gobierno_id", OtherKey="id", IsForeignKey=true)]
		public Gobiernos Gobiernos
		{
			get
			{
				return this._Gobiernos.Entity;
			}
			set
			{
				Gobiernos previousValue = this._Gobiernos.Entity;
				if (((previousValue != value) 
							|| (this._Gobiernos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Gobiernos.Entity = null;
						previousValue.paises.Remove(this);
					}
					this._Gobiernos.Entity = value;
					if ((value != null))
					{
						value.paises.Add(this);
						this._gobierno_id = value.id;
					}
					else
					{
						this._gobierno_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Gobiernos");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_paises_idiomas(paises_idiomas entity)
		{
			this.SendPropertyChanging();
			entity.paises = this;
		}
		
		private void detach_paises_idiomas(paises_idiomas entity)
		{
			this.SendPropertyChanging();
			entity.paises = null;
		}
		
		private void attach_paises_vecinos(paises_vecinos entity)
		{
			this.SendPropertyChanging();
			entity.paises = this;
		}
		
		private void detach_paises_vecinos(paises_vecinos entity)
		{
			this.SendPropertyChanging();
			entity.paises = null;
		}
		
		private void attach_paises_vecinos1(paises_vecinos entity)
		{
			this.SendPropertyChanging();
			entity.paises1 = this;
		}
		
		private void detach_paises_vecinos1(paises_vecinos entity)
		{
			this.SendPropertyChanging();
			entity.paises1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.paises_idiomas")]
	public partial class paises_idiomas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pais_id;
		
		private int _idioma_id;
		
		private System.Nullable<int> _hablantes;
		
		private System.Nullable<decimal> _porcentaje;
		
		private EntityRef<idiomas> _idiomas;
		
		private EntityRef<paises> _paises;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpais_idChanging(int value);
    partial void Onpais_idChanged();
    partial void Onidioma_idChanging(int value);
    partial void Onidioma_idChanged();
    partial void OnhablantesChanging(System.Nullable<int> value);
    partial void OnhablantesChanged();
    partial void OnporcentajeChanging(System.Nullable<decimal> value);
    partial void OnporcentajeChanged();
    #endregion
		
		public paises_idiomas()
		{
			this._idiomas = default(EntityRef<idiomas>);
			this._paises = default(EntityRef<paises>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pais_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int pais_id
		{
			get
			{
				return this._pais_id;
			}
			set
			{
				if ((this._pais_id != value))
				{
					if (this._paises.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpais_idChanging(value);
					this.SendPropertyChanging();
					this._pais_id = value;
					this.SendPropertyChanged("pais_id");
					this.Onpais_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idioma_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idioma_id
		{
			get
			{
				return this._idioma_id;
			}
			set
			{
				if ((this._idioma_id != value))
				{
					if (this._idiomas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onidioma_idChanging(value);
					this.SendPropertyChanging();
					this._idioma_id = value;
					this.SendPropertyChanged("idioma_id");
					this.Onidioma_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hablantes", DbType="Int")]
		public System.Nullable<int> hablantes
		{
			get
			{
				return this._hablantes;
			}
			set
			{
				if ((this._hablantes != value))
				{
					this.OnhablantesChanging(value);
					this.SendPropertyChanging();
					this._hablantes = value;
					this.SendPropertyChanged("hablantes");
					this.OnhablantesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_porcentaje", DbType="Decimal(15,5)")]
		public System.Nullable<decimal> porcentaje
		{
			get
			{
				return this._porcentaje;
			}
			set
			{
				if ((this._porcentaje != value))
				{
					this.OnporcentajeChanging(value);
					this.SendPropertyChanging();
					this._porcentaje = value;
					this.SendPropertyChanged("porcentaje");
					this.OnporcentajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="idiomas_paises_idiomas", Storage="_idiomas", ThisKey="idioma_id", OtherKey="id", IsForeignKey=true)]
		public idiomas idiomas
		{
			get
			{
				return this._idiomas.Entity;
			}
			set
			{
				idiomas previousValue = this._idiomas.Entity;
				if (((previousValue != value) 
							|| (this._idiomas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._idiomas.Entity = null;
						previousValue.paises_idiomas.Remove(this);
					}
					this._idiomas.Entity = value;
					if ((value != null))
					{
						value.paises_idiomas.Add(this);
						this._idioma_id = value.id;
					}
					else
					{
						this._idioma_id = default(int);
					}
					this.SendPropertyChanged("idiomas");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="paises_paises_idiomas", Storage="_paises", ThisKey="pais_id", OtherKey="id", IsForeignKey=true)]
		public paises paises
		{
			get
			{
				return this._paises.Entity;
			}
			set
			{
				paises previousValue = this._paises.Entity;
				if (((previousValue != value) 
							|| (this._paises.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._paises.Entity = null;
						previousValue.paises_idiomas.Remove(this);
					}
					this._paises.Entity = value;
					if ((value != null))
					{
						value.paises_idiomas.Add(this);
						this._pais_id = value.id;
					}
					else
					{
						this._pais_id = default(int);
					}
					this.SendPropertyChanged("paises");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.paises_vecinos")]
	public partial class paises_vecinos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pais_id;
		
		private int _vecino_id;
		
		private System.Nullable<int> _kms_frontera;
		
		private EntityRef<paises> _paises;
		
		private EntityRef<paises> _paises1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpais_idChanging(int value);
    partial void Onpais_idChanged();
    partial void Onvecino_idChanging(int value);
    partial void Onvecino_idChanged();
    partial void Onkms_fronteraChanging(System.Nullable<int> value);
    partial void Onkms_fronteraChanged();
    #endregion
		
		public paises_vecinos()
		{
			this._paises = default(EntityRef<paises>);
			this._paises1 = default(EntityRef<paises>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pais_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int pais_id
		{
			get
			{
				return this._pais_id;
			}
			set
			{
				if ((this._pais_id != value))
				{
					if (this._paises.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpais_idChanging(value);
					this.SendPropertyChanging();
					this._pais_id = value;
					this.SendPropertyChanged("pais_id");
					this.Onpais_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vecino_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int vecino_id
		{
			get
			{
				return this._vecino_id;
			}
			set
			{
				if ((this._vecino_id != value))
				{
					if (this._paises1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onvecino_idChanging(value);
					this.SendPropertyChanging();
					this._vecino_id = value;
					this.SendPropertyChanged("vecino_id");
					this.Onvecino_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kms_frontera", DbType="Int")]
		public System.Nullable<int> kms_frontera
		{
			get
			{
				return this._kms_frontera;
			}
			set
			{
				if ((this._kms_frontera != value))
				{
					this.Onkms_fronteraChanging(value);
					this.SendPropertyChanging();
					this._kms_frontera = value;
					this.SendPropertyChanged("kms_frontera");
					this.Onkms_fronteraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="paises_paises_vecinos", Storage="_paises", ThisKey="pais_id", OtherKey="id", IsForeignKey=true)]
		public paises paises
		{
			get
			{
				return this._paises.Entity;
			}
			set
			{
				paises previousValue = this._paises.Entity;
				if (((previousValue != value) 
							|| (this._paises.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._paises.Entity = null;
						previousValue.paises_vecinos.Remove(this);
					}
					this._paises.Entity = value;
					if ((value != null))
					{
						value.paises_vecinos.Add(this);
						this._pais_id = value.id;
					}
					else
					{
						this._pais_id = default(int);
					}
					this.SendPropertyChanged("paises");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="paises_paises_vecinos1", Storage="_paises1", ThisKey="vecino_id", OtherKey="id", IsForeignKey=true)]
		public paises paises1
		{
			get
			{
				return this._paises1.Entity;
			}
			set
			{
				paises previousValue = this._paises1.Entity;
				if (((previousValue != value) 
							|| (this._paises1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._paises1.Entity = null;
						previousValue.paises_vecinos1.Remove(this);
					}
					this._paises1.Entity = value;
					if ((value != null))
					{
						value.paises_vecinos1.Add(this);
						this._vecino_id = value.id;
					}
					else
					{
						this._vecino_id = default(int);
					}
					this.SendPropertyChanged("paises1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class PaisContinenteResult
	{
		
		private string _pais;
		
		private string _continente;
		
		public PaisContinenteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pais", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string pais
		{
			get
			{
				return this._pais;
			}
			set
			{
				if ((this._pais != value))
				{
					this._pais = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_continente", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string continente
		{
			get
			{
				return this._continente;
			}
			set
			{
				if ((this._continente != value))
				{
					this._continente = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
